[package]
name = "hmrc-currency-rates"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
chttp = "0.5.5"
clap = { version = "4.5.27", features = ["derive"] }
csv = "1.3.1"
roxmltree = "0.20.0"
tokio = { version = "1.43.0", features = ["full"] }
